cursor-style: set the cursor style

diff --git a/scripts/blame b/scripts/blame
--- a/scripts/blame
+++ b/scripts/blame
@@ -1,23 +1,30 @@
 #!/bin/bash
 # blame: git blame wrapper
 
-if ! ingit
-then
-    >&2 echo "blame failed: Not in a git repo"
-    exit 1
-fi
+check_git ()
+{
+    if ! ingit
+    then
+        >&2 echo "blame failed: Not in a git repo"
+        return 1
+    fi
+}
 
 if [ $# -gt 0 ]
 then
     (
         for f in "$@"
         do
+            cd "$(dirname "$(realpath "$f")")"
+            check_git || exit 1
             git --no-pager blame  -- "$f"
         done
     ) | less
 else 
     while read -r path line
     do
+        cd "$(dirname "$(realpath "$path")")"
+        check_git || exit 1
         git --no-pager blame -L "$line,$line" -- "$path"
     done < <(cat)
 fi
diff --git a/scripts/playalbum b/scripts/playalbum
--- a/scripts/playalbum
+++ b/scripts/playalbum
@@ -6,12 +6,16 @@
 
 if [ $# -eq 1 ]
 then
-    if [ ! -f "$1" ]
+    if [ -f "$1" ]
     then
-        >&2 echo "error: $f is not a file."
+        dir="$(dirname "$1")"
+    elif [ -d "$1" ]
+    then
+        dir="$1"
+    else
+        >&2 echo "error: $f is not a file or directory."
         exit 1
     fi
-    dir="$(dirname "$1")"
     cd "$dir"
     shift
 fi
