wip

diff --git a/scripts/desktop-get-focus b/scripts/desktop-get-focus
--- a/scripts/desktop-get-focus
+++ b/scripts/desktop-get-focus
@@ -1,3 +1,10 @@
 #!/bin/bash
-# desktop-focus:
+# desktop-focus: get current desktop number
 
+out="$(wmctrl -d | awk '$2 == "*" {print $1}')"
+if [ -z "$out" ]
+then
+    >&2 echo "error: Could not determine active desktop"
+    exit 1
+fi
+echo "$out"
diff --git a/scripts/desktop-next b/scripts/desktop-next
--- a/scripts/desktop-next
+++ b/scripts/desktop-next
@@ -1,3 +1,12 @@
 #!/bin/bash
-# desktop-next:
+# desktop-next: go to the next virtual desktop
 
+count="$(desktop-get-count)" || exit 1
+focus="$(desktop-get-focus)" || exit 1
+if [ $focus -lt $((count - 1)) ]
+then
+    wmctrl -s "$((focus + 1))"
+else
+    # Fail silently.
+    .
+fi
diff --git a/scripts/desktop-prev b/scripts/desktop-prev
--- a/scripts/desktop-prev
+++ b/scripts/desktop-prev
@@ -1,3 +1,11 @@
 #!/bin/bash
-# desktop-prev:
+# desktop-prev: go to the previous virtual desktop
 
+count="$(desktop-get-count)" || exit 1
+if [ $focus -gt 1 ]
+then
+    wmctrl -s "$((focus - 1))"
+else
+    # Fail silently.
+    .
+fi
