lff rename

diff --git a/scripts/lff b/scripts/lff
--- a/scripts/lff
+++ b/scripts/lff
@@ -1,18 +1,61 @@
 #!/bin/bash
-# lff: lf focus, tool for working with lf's synchronized focus file.
+# lff: execute with lffocus
 
-lff ()
-{
-    local lf_runtime_dir="$XDG_RUNTIME_DIR/lf"
-    local focus_file="$lf_runtime_dir/primary_focus"
+if [ $# -eq 0 ]
+then
+    # Show focus on no args.
+    lffocus
+    exit 0
+fi
 
-    if [ ! -f "$focus_file" ]
+# Validate that the first argument
+# is a command name.
+# Otherwise, command echo may accidentally intepret a flag.
+command_name="$1"
+if [[ $command_name =~ ^\s*-.*$ ]]
+then
+    >&2 echo "Invalid command name \"$command_name\"."
+    exit 1
+fi
+
+xargs_replace_str_mode=0
+for arg in "$@"
+do
+    if echo "$arg" | grep -q '{}'
     then
-        >&2 "error: no focus file"
-        return 1
+        xargs_replace_str_mode=1
+        break
     fi
+done
 
-    cat "$focus_file"
-}
+focus="$(lffocus | tr -d '\n')"
+if [ -z "$focus" ]
+then
+    exit 1
+fi
 
-lff "$@"
+XARGS="xargs -0"
+
+if [ $xargs_replace_str_mode -eq 1 ]
+then
+    echo -n "$focus" | $XARGS -i echo "$@"
+else
+    echo -n "$focus" | $XARGS echo "$@"
+fi
+
+#https://stackoverflow.com/questions/3231804/in-bash-how-to-add-are-you-sure-y-n-to-any-command-or-alias
+>&2 read -r -p "Are you sure? [y/N] " response
+case "$response" in
+    [yY][eE][sS]|[yY]) 
+        ;;
+    *)
+        >&2 echo "aborted"
+        exit 1
+        ;;
+esac
+if [ $xargs_replace_str_mode -eq 1 ]
+then
+    echo -n "$focus" | $XARGS -i "$@"
+else
+    echo -n "$focus" | $XARGS "$@"
+fi
