more readme

diff --git a/scripts/readme b/scripts/readme
--- a/scripts/readme
+++ b/scripts/readme
@@ -1,9 +1,10 @@
 #!/bin/bash
 # readme: Utility for readme files and other software information.
-# -d <package_name>: Output README for a dpkg package.
-# -D <package_name>: Output README.Debian for a dpkg package.
+# -d <package_name>: Output README for a package.
+# -D <package_name>: Output README.Debian for a package.
 # -p No pager
-# -m <package_name>: Output man pages for a dpkg package.
+# -m <package_name>: Output man pages for a package.
+# -i <package_name>: Information about what is available for this package.
 
 usage ()
 {
@@ -43,7 +44,7 @@ else
     pager_command=cat
 fi
 
-while getopts ":hpd:D:m:-:" opt
+while getopts ":hpd:i:D:m:-:" opt
 do
     case $opt in
         h)
@@ -60,6 +61,9 @@ do
             ;;
         m)
             set_func dpkg_manpages "$OPTARG"
+            ;;
+        i)
+            set_func dpkg_information "$OPTARG"
             ;;
         *)
             case $OPTARG in
@@ -92,7 +96,7 @@ do_check_dpkg_installed ()
     local package_name="$1"
     if ! dpkg -l "$package_name" >/dev/null 2>&1
     then
-        2>&1 echo "error: Package \"$package_name\" is not installed."
+        2>&1 echo "error: Package \"$package_name\" is not found."
         return 1
     fi
     if ! dpkg -l "$package_name" 2>/dev/null | tail -1 | grep -q -E '^ii '
@@ -102,13 +106,41 @@ do_check_dpkg_installed ()
     fi
 }
 
-dpkg_readme_common ()
+get_dpkg_readme_files ()
 {
+    local package_name="$1"
+    shift
     local extensions=()
-    [ "$1" = "normal" ] && extensions=("" ".md") || extensions=(".Debian")
-    local package_name="$2"
+    while [ "$#" -gt 0 ]
+    do
+        extensions+=("$1")
+        shift
+    done
 
     do_check_dpkg_installed "$package_name" || return 1
+
+    local package_dir="/usr/share/doc/$package_name"
+
+    for extension in "${extensions[@]}"
+    do
+        if [ -f "$package_dir/README$extension" ]
+        then
+            echo "$package_dir/README$extension"
+        elif [ -f "$package_dir/README$extension.gz" ]
+        then
+            echo "$package_dir/README$extension.gz"
+        else
+            echo "<none>"
+        fi
+    done
+}
+
+dpkg_readme_common ()
+{
+    local extensions_mode="$1"
+    local extensions=()
+    [ "$extensions_mode" = "normal" ] && extensions=("" ".md") || extensions=(".Debian")
+    local package_name="$2"
 
     local package_dir="/usr/share/doc/$package_name"
     if [ ! -d "$package_dir" ]
@@ -117,23 +149,32 @@ dpkg_readme_common ()
         return 1
     fi
 
-    for extension in "${extensions[@]}"
+    local files="$(get_dpkg_readme_files "$package_name" "${extensions[@]}")"
+    local i=0
+    while read -r f
     do
-        if [ -f "$package_dir/README$extension" ]
+        local extension="${extensions[$i]}"
+        if [ "$f" != "<none>" ]
         then
-            cat "$package_dir/README$extension" | $pager_command
-            return 0
-        elif [ -f "$package_dir/README$extension.gz" ]
-        then
-            gunzip -c "$package_dir/README$extension.gz" | $pager_command
-            return 0
+            case $(mimetype -b "$f") in
+                application/gzip)
+                    gunzip -c "$f" | "$pager_command"
+                    return 0
+                    ;;
+                *)
+                    cat "$f" | "$pager_command"
+                    return 0
+                    ;;
+            esac
         fi
-    done
-
+        ((i++))
+    done < <(echo "$files")
+    # no readme was found
     for extension in "${extensions[@]}"
     do
         2>&1 echo "error: README$extension file not found in $package_dir"
     done
+
     return 1
 }
 
@@ -147,38 +188,80 @@ func_dpkg_readme_debian ()
     dpkg_readme_common debian "$@"
 }
 
-section_descriptions=(
-"1) Executable programs or shell commands"
-"2) System calls (functions provided by the kernel)"
-"3) Library calls (functions within program libraries)"
-"4) Special files (usually found in /dev)"
-"5) File formats and conventions, e.g. /etc/passwd"
-"6) Games"
-"7) Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7)"
-"8) System administration commands (usually only for root)"
-"9) Kernel routines [Non standard]"
-)
-
 func_dpkg_manpages ()
 {
     local package_name="$1"
 
     do_check_dpkg_installed "$package_name" || return 1
-    dpkg_manpages_files="$(dpkg -L "$package_name" | grep -E '^/usr/share/man/man[[:digit:]]/' | xargs -r basename -a | sort | uniq)"
-    if [ -z "$dpkg_manpages_files" ]
-    then
-        return 0
-    fi
+    mapfile -t dpkg_manpages_files < <(dpkg -L "$package_name" \
+                                        | grep -E '^/usr/share/man/man[[:digit:]]/' \
+                                        | xargs -r basename -a \
+                                        | sort \
+                                        | uniq)
+
+    #note: Not using pager for this output as intended to be copied.
     (
         for i in {1..9}
         do
-            section_manpages="$(echo "$dpkg_manpages_files" | grep -E '\.'$i'\.gz$' | xargs -r basename -s .$i.gz)"
+            local section_manpages=()
+            for f in ${dpkg_manpages_files[@]}
+            do
+                if echo "$f" | grep -q -E '\.'$i'\.gz$'
+                then
+                    section_manpages+=("$(basename -s .$i.gz "$f")")
+                fi
+            done
+            for var in ${section_manpages[@]}
+            do
+                echo "$var" | sed "s/^/man $i /"
+            done
+        done
+    )
+}
+
+manpage_section_descriptions=(
+"<zero section doesn't exist>"
+"Executable programs or shell commands"
+"System calls (functions provided by the kernel)"
+"Library calls (functions within program libraries)"
+"Special files (usually found in /dev)"
+"File formats and conventions, e.g. /etc/passwd"
+"Games"
+"Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7)"
+"System administration commands (usually only for root)"
+"Kernel routines [Non standard]"
+)
+
+func_dpkg_information ()
+{
+    local package_name="$1"
+    if ! dpkg -l "$package_name" >/dev/null 2>&1
+    then
+        2>&1 echo "error: Package \"$package_name\" not found."
+        return 1
+    fi
+    echo "name: $package_name"
+    dpkg-query --show -f='status: ${Status}\nstatus-abbrev: "${db:Status-Abbrev}"\n' "$package_name"
+
+    local manpages="$(func_dpkg_manpages "$package_name" 2>/dev/null)"
+    if [ ! -z "$manpages" ]
+    then
+        for i in {1..9}
+        do
+            local section_manpages="$(echo -n "$manpages" | grep -E "^man $i " | cutw 3)"
             if [ ! -z "$section_manpages" ]
             then
-                echo "$section_manpages" | sed "s/^/$i /"
+                echo "man$i: ${manpage_section_descriptions[$i]}"
+                echo "$section_manpages" | while read -r page ; do
+                    whatis "$page" | grep -E "^$page \($i\) " | sed 's/^/    /'
+                done
             fi
         done
-    ) | $pager_command
+    fi
+    printf "README files: "
+    get_dpkg_readme_files "$package_name" '' '.md' | grep -v -E '^<none>$' | head -1
+    printf "README.Debian file: "
+    get_dpkg_readme_files "$package_name" '.Debian' | grep -v -E '^<none>$' | head -1
 }
 
 func_$func "${func_args[@]}"
