working on a sort of json rpc to more easily invoke vim behaviour from --remote-send

diff --git a/scripts/vimjsonrpc b/scripts/vimjsonrpc
--- a/scripts/vimjsonrpc
+++ b/scripts/vimjsonrpc
@@ -1,15 +1,18 @@
 #!/bin/bash
+#
+# TODO:
+# Argument passing.
+# Input checking.
+
+if ! command -v jq &>/dev/null
+then
+    >&2 echo "jq must be installed"
+    exit 1
+fi
 
 if [ -z "$VIM_SERVERNAME" ]
 then
     >&2 echo "Not in a vim server"
-    exit 1
-fi
-
-json_contents="$(cat)"
-if ! echo "$json_contents" | jq . &>/dev/null
-then
-    >&2 echo "Invalid json"
     exit 1
 fi
 
@@ -21,7 +24,17 @@ fi
 
 vim_function_name="$1"
 shift
-
+# Make sure vim function name is in the correct form.
+# This is a string starting with a letter, which can contain numbers and dots
+# (for dictionary access to funcrefs, see :help function).
+#todo: following . must be identifiers too, e.g. no foo.3
+vim_function_regex='^[A-Za-z][A-Za-z0-9\.]*$'
+if [[ ! "$vim_function_name" =~ $vim_function_regex ]]
+then
+    >&2 echo "Ill-formed vim function name given: $vim_function_name"
+    exit 1
+fi
+    
 vim_function_extra_args=()
 while [[ $# -gt 0 ]]
 do
@@ -29,11 +42,15 @@ do
     shift
 done
 
+json_contents="$(cat)"
+if ! echo "$json_contents" | jq . &>/dev/null
+then
+    >&2 echo "Invalid json"
+    exit 1
+fi
+
 json_temp_file="$(mktemp)"
 echo "$json_contents" > "$json_temp_file"
 
-vim --servername "$VIM_SERVERNAME" --remote-send '<C-\><C-n>:call VimFunction(json_decode(readfile('"$temp"')))<cr>'
-
-send_string='<C-\><C-n>:call '"$vim_function_name"'(json_decode(readfile('"$json_temp_file"')))<cr>'
-
+send_string='<C-\><C-n>:call VimJSONRPC("'"$vim_function_name"'", "'"$json_temp_file"'")<cr>'
 vim --servername "$VIM_SERVERNAME" --remote-send "$send_string"
