wip

diff --git a/scripts/wln b/scripts/wln
--- a/scripts/wln
+++ b/scripts/wln
@@ -1,7 +1,9 @@
 #!/bin/bash
 # wln: "web ln", create a URL link as an XDG desktop entry.
 # 
-# todo: Resolve name to protocol, e.g. can just write duckduckgo.com.
+# todo:
+#  Resolve name to protocol, e.g. can just write duckduckgo.com.
+#  Why does caja only work with .desktop extension? Maybe want to use .link, or no extension.
 
 if [ $# -ne 2 ]
 then
@@ -13,15 +15,15 @@ link_name="$2"
 
 stub="[Desktop Entry]
 Type=Link
-Name=test_link
+Name=$link_name
 URL=$url
 "
-if [ -e "$link_name" ]
+if [ -e "$link_name.desktop" ]
 then
-    >&2 echo "Cannot create \"$link_name\": already in use."
+    >&2 echo "Cannot create \"$link_name.desktop\": already in use."
     exit 1
 fi
-echo "$stub" > "$link_name"
+echo "$stub" > "$link_name.desktop"
 
 
 # Variant which creates an HTML stub instead.
